"""Initial_migration

Revision ID: 23c6c96c3b41
Revises: 
Create Date: 2026-02-18 21:24:02.806441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c6c96c3b41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('scholar_url', sa.String(), nullable=True),
    sa.Column('email_guess', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professors_id'), 'professors', ['id'], unique=False)
    op.create_index(op.f('ix_professors_name'), 'professors', ['name'], unique=False)
    op.create_table('email_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('content_short', sa.Text(), nullable=True),
    sa.Column('content_long', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_drafts_id'), 'email_drafts', ['id'], unique=False)
    op.create_table('pipeline_timestamps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_touch_at', sa.DateTime(), nullable=True),
    sa.Column('next_action_at', sa.DateTime(), nullable=True),
    sa.Column('followup_recommended', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professor_id')
    )
    op.create_index(op.f('ix_pipeline_timestamps_id'), 'pipeline_timestamps', ['id'], unique=False)
    op.create_table('professor_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('card_json', sa.Text(), nullable=True),
    sa.Column('card_md', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professor_cards_id'), 'professor_cards', ['id'], unique=False)
    op.create_table('source_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('fetch_status', sa.String(), nullable=True),
    sa.Column('error_msg', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_pages_id'), 'source_pages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_pages_id'), table_name='source_pages')
    op.drop_table('source_pages')
    op.drop_index(op.f('ix_professor_cards_id'), table_name='professor_cards')
    op.drop_table('professor_cards')
    op.drop_index(op.f('ix_pipeline_timestamps_id'), table_name='pipeline_timestamps')
    op.drop_table('pipeline_timestamps')
    op.drop_index(op.f('ix_email_drafts_id'), table_name='email_drafts')
    op.drop_table('email_drafts')
    op.drop_index(op.f('ix_professors_name'), table_name='professors')
    op.drop_index(op.f('ix_professors_id'), table_name='professors')
    op.drop_table('professors')
    # ### end Alembic commands ###
